authserver:
 image: sxi/authserver
 ports:
  - "9999:9999"
product:
 image: sxi/product
 ports:
  - "8083:8083"
 links:
  - mongo
  - authserver
mongodata:
 image: mongo:3.0.6
 volumes:
  - /data/db
 command: --break-mongo
mongo:
 image: mongo:3.0.6
 volumes_from:
  - mongodata
 ports:
  - "27017:27017"
 command: --smallfiles
ui:
 image: sxi/ui
 ports:
  - "8081:8081"
 links:
  - authserver
  - product